//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting_
    {
        public int ID { get; set; }
        public int Customer_ID { get; set; }
        public int Type_ID { get; set; }
        public int Amount { get; set; }
        public string Discription { get; set; }
        public System.DateTime Date_time { get; set; }
    
        public virtual Accounting_Types Accounting_Types { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
